# Generated by Django 6.0.6 on 2026-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name=' بيام')),
                ('name', models.CharField(max_length=250, verbose_name=' نام')),
                ('email', models.EmailField(max_length=254, verbose_name=' ايميل ')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=250, verbose_name=' موضوع')),
            ],
        ),
    ]
