# Generated by Django 6.0.6 on 2026-06-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_reading_time_alter_comment_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_counts',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
